Repository anchore/grype, pull requests merged in 2023-09, with the labels that each got.

#1484 chore: Update go declaration to have point version
  go.mod
Labels: changelog-ignore

#1397 Ignore/add match results based on OpenVEX documents
  .gitignore
  README.md
  cmd/grype/cli/commands/root.go
  cmd/grype/cli/options/grype.go
  cmd/grype/cli/ui/__snapshots__/handle_vulnerability_scanning_started_test.snap
  cmd/grype/cli/ui/handle_vulnerability_scanning_started.go
  cmd/grype/cli/ui/handle_vulnerability_scanning_started_test.go
  go.mod
  go.sum
  grype/deprecated.go
  grype/event/monitor/matching.go
  grype/match/ignore.go
  grype/match/match.go
  grype/match/matcher_type.go
  grype/match/matches.go
  grype/match/matches_test.go
  grype/matcher/matchers.go
  grype/presenter/internal/test_helpers.go
  grype/presenter/models/ignore.go
  grype/presenter/models/metadata_mock.go
  grype/presenter/table/__snapshots__/presenter_test.snap
  grype/presenter/table/presenter.go
  grype/presenter/table/presenter_test.go
  grype/presenter/table/test-fixtures/snapshot/TestDisplaysIgnoredMatches.golden
  grype/presenter/table/test-fixtures/snapshot/TestEmptyTablePresenter.golden
  grype/presenter/table/test-fixtures/snapshot/TestHidesIgnoredMatches.golden
  grype/presenter/table/test-fixtures/snapshot/TestTablePresenter.golden
  grype/vex/openvex/implementation.go
  grype/vex/openvex/implementation_test.go
  grype/vex/processor.go
  grype/vex/processor_test.go
  grype/vex/testdata/vex-docs/openvex-demo1.json
  grype/vex/testdata/vex-docs/openvex-demo2.json
  grype/vulnerability_matcher.go
  test/integration/match_by_image_test.go
  test/integration/test-fixtures/vex/openvex/affected.openvex.json
  test/integration/test-fixtures/vex/openvex/under_investigation.openvex.json
Labels: enhancement

#1494 fix: version output including supported db schema
  cmd/grype/cli/cli.go
  go.mod
  go.sum
Labels: bug

#1507 Update chronicle to v0.8.0
  .chronicle.yaml
  .github/actions/bootstrap/action.yaml
  .github/workflows/release.yaml
  Makefile
Labels: changelog-ignore

#1521 chore: remove outdated comment about fuzzy matching python versions
  grype/version/constraint.go
Labels: changelog-ignore
