Repository anchore/grype, pull requests merged in 2024-07, with the labels that each got.

#1974 docs: update readme with new default cyclone-dx format v1.6
  README.md
Labels: changelog-ignore

#1996 chore: request artifact in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, changelog-ignore

#2008 Disable ui before run function on db status
  cmd/grype/cli/commands/db_status.go
Labels: bug
