Repository anchore/grype, pull requests merged in 2024-06, with the labels that each got.

#1910 Use tool for DCO checks
  .github/workflows/dco.yaml
Labels: changelog-ignore

#1914 Remove DCO workflow
  .github/workflows/dco.yaml
Labels: changelog-ignore

#1915 Add skopeo to managed utilities
  .binny.yaml
  test/integration/utils_test.go
Labels: changelog-ignore

#1933 Sort order for matches should consider fix info
  grype/match/matches_test.go
  grype/match/sort.go
  grype/presenter/table/presenter.go
  grype/presenter/table/presenter_test.go
Labels: bug

#1934 Updating maven URLs in README.md
  README.md
Labels: documentation

#1944 fix match sort ordering for different locations
  grype/match/matches_test.go
  grype/match/sort.go
Labels: bug

#1950 fix: use location `RealPath` not `String()` for match sorting
  grype/match/sort.go
Labels: bug

#1953 chore: enable dependabot to keep boostrap action updated
  .github/actions/bootstrap/action.yaml
  .github/dependabot.yaml
Labels: changelog-ignore

#1961 chore: add workflow to update quality test db
  .github/workflows/update-quality-gate-db.yml
  Taskfile.yaml
  test/quality/Makefile
  test/quality/test-db-url
Labels: changelog-ignore
