Repository anchore/grype, pull requests merged in 2024-05, with the labels that each got.

#1842 Upgrade tool management
  .binny.yaml
  .github/actions/bootstrap/action.yaml
  .github/scripts/go-mod-tidy-check.sh
  .github/scripts/syft-released-version-check.sh
  .github/scripts/update-version-file.sh
  .github/workflows/release-version-file.yaml
  .github/workflows/release.yaml
  .github/workflows/update-bootstrap-tools.yml
  .github/workflows/validations.yaml
  .gitignore
  .goreleaser.yaml
  Makefile
  README.md
  Taskfile.yaml
  schema/cyclonedx/Makefile
Labels: changelog-ignore

#1860 chore: add top level permissions to new workflow
  .github/workflows/release-version-file.yaml
Labels: changelog-ignore

#1872 Disable TUI for simple commands
  cmd/grype/cli/cli.go
  cmd/grype/cli/commands/completion.go
  cmd/grype/cli/commands/db_check.go
  cmd/grype/cli/commands/db_delete.go
  cmd/grype/cli/commands/db_import.go
  cmd/grype/cli/commands/db_list.go
  cmd/grype/cli/commands/db_status.go
  cmd/grype/cli/commands/explain.go
  cmd/grype/cli/commands/util.go
Labels: bug

#1876 feat: add config command
  cmd/grype/cli/cli.go
  cmd/grype/cli/options/database.go
  cmd/grype/cli/options/datasources.go
  cmd/grype/cli/options/grype.go
  cmd/grype/cli/options/match.go
  cmd/grype/cli/options/registry.go
  cmd/grype/cli/options/search.go
  go.mod
  go.sum
Labels: enhancement

#1895 Update syft to 1.4.2-0.20240528141306-ac34808b9c55
  go.mod
  go.sum
  grype/db/v3/namespace_test.go
  grype/pkg/package_test.go
  grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterDir.golden
  grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterImage.golden
  grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
  grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
  test/integration/compare_sbom_input_vs_lib_test.go
Labels: dependencies
