Repository anchore/grype, pull requests merged in 2024-11, with the labels that each got.

#2232 Add v6 provider store
  grype/db/v6/db.go
  grype/db/v6/models.go
  grype/db/v6/provider_store.go
  grype/db/v6/provider_store_test.go
  grype/db/v6/store.go
Labels: changelog-ignore

#2248 Restore log on UI teardown
  cmd/grype/internal/ui/ui.go
Labels: bug

#2150 Add v6 distribution client
  go.mod
  grype/db/internal/schemaver/schema_ver.go
  grype/db/internal/schemaver/schema_ver_test.go
  grype/db/v6/description.go
  grype/db/v6/description_test.go
  grype/db/v6/distribution/client.go
  grype/db/v6/distribution/client_test.go
  grype/db/v6/distribution/latest.go
  grype/db/v6/distribution/latest_test.go
  grype/db/v6/distribution/status.go
Labels: enhancement, changelog-ignore

#2243 Add v6 vulnerability & blob stores
  go.mod
  grype/db/internal/gormadapter/open.go
  grype/db/internal/gormadapter/open_test.go
  grype/db/v6/blob_store.go
  grype/db/v6/blob_store_test.go
  grype/db/v6/blobs.go
  grype/db/v6/db.go
  grype/db/v6/models.go
  grype/db/v6/store.go
  grype/db/v6/vulnerability_store.go
  grype/db/v6/vulnerability_store_test.go
Labels: changelog-ignore

#2245 Add AffectedPackage store
  grype/db/v6/affected_package_store.go
  grype/db/v6/affected_package_store_test.go
  grype/db/v6/blobs.go
  grype/db/v6/db.go
  grype/db/v6/enumerations.go
  grype/db/v6/enumerations_test.go
  grype/db/v6/models.go
  grype/db/v6/store.go
  grype/db/v6/vulnerability_store.go
Labels: changelog-ignore

#2151 Add v6 DB curator
  grype/db/v6/affected_package_store_test.go
  grype/db/v6/blob_store_test.go
  grype/db/v6/db.go
  grype/db/v6/db_metadata_store_test.go
  grype/db/v6/description.go
  grype/db/v6/description_test.go
  grype/db/v6/distribution/client.go
  grype/db/v6/installation/curator.go
  grype/db/v6/installation/curator_test.go
  grype/db/v6/internal/db.go
  grype/db/v6/models.go
  grype/db/v6/provider_store_test.go
  grype/db/v6/status.go
  grype/db/v6/store.go
  grype/db/v6/vulnerability_store_test.go
  internal/file/hasher.go
Labels: enhancement, changelog-ignore

#2261 Fix failing tests
  grype/db/v6/affected_cpe_store_test.go
Labels: changelog-ignore

#2275 core dependencies: latest syft v1.17.0 and latest stereoscope v0.0.9
  go.mod
  go.sum
Labels: dependencies

#2265 Add data-driven approach to v6 distro search
  grype/db/v6/affected_package_store.go
  grype/db/v6/affected_package_store_test.go
  grype/db/v6/models.go
  grype/db/v6/models_test.go
Labels: changelog-ignore

#2278 Remove DB v1 & v2 schemas
  grype/db/v1/id.go
  grype/db/v1/namespace.go
  grype/db/v1/namespace_test.go
  grype/db/v1/schema_version.go
  grype/db/v1/store.go
  grype/db/v1/store/model/id.go
  grype/db/v1/store/model/vulnerability.go
  grype/db/v1/store/model/vulnerability_metadata.go
  grype/db/v1/store/store.go
  grype/db/v1/store/store_test.go
  grype/db/v1/vulnerability.go
  grype/db/v1/vulnerability_metadata.go
  grype/db/v2/id.go
  grype/db/v2/namespace.go
  grype/db/v2/namespace_test.go
  grype/db/v2/schema_version.go
  grype/db/v2/store.go
  grype/db/v2/store/model/id.go
  grype/db/v2/store/model/vulnerability.go
  grype/db/v2/store/model/vulnerability_metadata.go
  grype/db/v2/store/store.go
  grype/db/v2/store/store_test.go
  grype/db/v2/vulnerability.go
  grype/db/v2/vulnerability_metadata.go
  grype/db/v2/vulnerability_metadata_store.go
  grype/db/v2/vulnerability_store.go
Labels: breaking-change
