Repository anchore/grype, pull requests merged in 2024-10, with the labels that each got.

#2152 Explicitly skip update ts on check failure
  grype/db/legacy/distribution/curator.go
Labels: bug, changelog-ignore

#1553 feat: wordpress-plugin support
  grype/search/only_vulnerable_targets.go
  grype/search/only_vulnerable_targets_test.go
Labels: enhancement

#2162 fix: use fix info from secDB in APK matcher even if NVD fix info present
  grype/matcher/apk/matcher.go
  grype/matcher/apk/matcher_test.go
Labels: bug

#2177 Add release docs
  RELEASE.md
Labels: documentation

#2182 Skip matching on packages with missing version info
  cmd/grype/cli/commands/root.go
  cmd/grype/cli/commands/root_test.go
  grype/matcher/apk/matcher_test.go
  grype/search/cpe.go
  grype/search/cpe_test.go
  grype/search/distro.go
  grype/search/distro_test.go
  grype/search/language.go
  grype/search/language_test.go
  grype/vulnerability_matcher_test.go
Labels: bug

#2189 dependency: bump syft to main pre-release
  go.mod
  go.sum
Labels: dependencies

#2197 fix: azurelinux considered as comprehensive distro
  grype/pkg/package.go
Labels: bug

#2201 Updated README.md with period & correct phrase.
  README.md
Labels: documentation

#2194 feat: multi-level configuration and profiles
  cmd/grype/cli/cli.go
  cmd/grype/cli/commands/util.go
  go.mod
  go.sum
  test/cli/config_test.go
  test/cli/test-fixtures/configs/dir1/.grype.yaml
  test/cli/test-fixtures/configs/dir2/.grype.yaml
  test/cli/test-fixtures/configs/dir3/.grype.yaml
Labels: enhancement

#2219 bump syft to v1.15.0, sterescope to v0.0.5
  go.mod
  go.sum
Labels: dependencies

#2227 Remove gentoo integration test
  test/integration/match_by_image_test.go
Labels: changelog-ignore
