Repository anchore/grype, pull requests merged in 2024-09, with the labels that each got.

#1602 fix(apk): find secdb entries for origin packages
  grype/matcher/apk/matcher.go
  grype/matcher/apk/matcher_test.go
Labels: bug

#2133 bug: fix slice init length
  grype/presenter/sarif/presenter_test.go
Labels: changelog-ignore

#2090 chore: switch to yardstick validate from custom gate.py
  .github/actions/bootstrap/action.yaml
  test/quality/.yardstick.yaml
  test/quality/Makefile
  test/quality/gate.py
  test/quality/requirements.txt
Labels: changelog-ignore

#2114 Correctly match JVM version ranges
  .gitignore
  cmd/grype/cli/options/match.go
  go.mod
  go.sum
  grype/cpe/cpe.go
  grype/internal/packagemetadata/generated.go
  grype/internal/packagemetadata/names.go
  grype/internal/packagemetadata/names_test.go
  grype/matcher/stock/matcher_test.go
  grype/pkg/java_metadata.go
  grype/pkg/java_metadata_test.go
  grype/pkg/package.go
  grype/pkg/package_test.go
  grype/search/cpe.go
  grype/version/constraint.go
  grype/version/format.go
  grype/version/format_test.go
  grype/version/generic_constraint.go
  grype/version/golang_constraint.go
  grype/version/jvm_constraint.go
  grype/version/jvm_constraint_test.go
  grype/version/jvm_version.go
  grype/version/jvm_version_test.go
  grype/version/version.go
  internal/regex_helpers.go
  internal/regex_helpers_test.go
  test/integration/db_mock_test.go
  test/integration/match_by_image_test.go
  test/integration/test-fixtures/image-jvm-match-coverage/Dockerfile
  test/integration/test-fixtures/image-jvm-match-coverage/opt/java/openjdk/release
Labels: bug

#2141 Add awaiting response management
  .github/workflows/remove-awaiting-response-label.yaml
Labels: changelog-ignore

#2148 Add low pass filter to DB update checks
  cmd/grype/cli/commands/db_check.go
  cmd/grype/cli/commands/db_update.go
  cmd/grype/cli/options/database.go
  go.mod
  grype/db/legacy/distribution/curator.go
  grype/db/legacy/distribution/curator_test.go
  grype/load_vulnerability_db.go
  test/cli/db_validations_test.go
Labels: enhancement

#2139 Use faster xz lib for decompression
  go.mod
  go.sum
  internal/file/getter.go
  internal/file/tar_xz_decompressor.go
  internal/file/tar_xz_decompressor_test.go
  internal/file/xz_decompressor.go
  internal/file/xz_decompressor_test.go
Labels: changelog-ignore
