Repository anchore/grype, pull requests merged in 2025-02, with the labels that each got.

#2432 Add advisory tag constant
  grype/db/v6/enumerations.go
Labels: changelog-ignore

#2431 More complete severity parsing for v6 DBs
  go.mod
  go.sum
  grype/db/v6/blobs.go
  grype/db/v6/cvss.go
  grype/db/v6/severity.go
  grype/db/v6/severity_test.go
  grype/db/v6/vulnerability_provider.go
  grype/db/v6/vulnerability_store_test.go
Labels: changelog-ignore

#2442 fix: only log matcher errors
  grype/vulnerability_matcher.go
Labels: bug

#2448 Add language mapping to knpwn package specifier overrides (v6)
  grype/db/v6/data.go
Labels: changelog-ignore

#2463 Add CPE provider
  grype/internal/packagemetadata/discover_type_names.go
  grype/pkg/cpe_provider.go
  grype/pkg/cpe_provider_test.go
  grype/pkg/provider.go
  grype/pkg/purl_provider.go
  grype/presenter/models/source.go
  grype/presenter/models/source_test.go
Labels: enhancement

#2472 Add EPSS models to the v6 DB
  grype/db/v6/db.go
  grype/db/v6/db_metadata_store.go
  grype/db/v6/db_metadata_store_test.go
  grype/db/v6/installation/curator_test.go
  grype/db/v6/models.go
  grype/db/v6/vulnerability_decorator_store.go
  grype/db/v6/vulnerability_provider.go
  grype/presenter/models/vulnerability_metadata.go
  grype/vulnerability/metadata.go
Labels: enhancement, changelog-ignore

#2488 fix: allow querying for CPE with only vendor or product
  grype/db/v6/vulnerability_provider.go
  grype/db/v6/vulnerability_provider_test.go
Labels: changelog-ignore
