Repository anchore/grype, pull requests merged in 2025-03, with the labels that each got.

#2497 Cover mariner and ubuntu namespace conversion
  grype/db/v6/vulnerability.go
  grype/db/v6/vulnerability_test.go
Labels: bug, changelog-ignore

#2499 Ensure azurelinux ids get same version processing as mariner
  grype/db/v6/vulnerability.go
  grype/db/v6/vulnerability_test.go
Labels: changelog-ignore

#2502 Enumerate version ranges within a single match (don't duplicate)
  grype/db/v6/vulnerability.go
  grype/db/v6/vulnerability_provider.go
  grype/matcher/apk/matcher.go
  grype/matcher/internal/cpe.go
  grype/matcher/internal/distro.go
  grype/matcher/internal/language.go
  test/integration/match_by_image_test.go
Labels: changelog-ignore

#2504 Remove v6 development configuration
  test/quality/.grype.yaml
  test/quality/.yardstick.yaml
Labels: changelog-ignore

#2271 Add suggested fixed version when there are multiple fixes available
  go.mod
  grype/presenter/internal/test_helpers.go
  grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
  grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
  grype/presenter/models/document_test.go
  grype/presenter/models/match.go
  grype/presenter/models/vulnerability.go
  grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_directory.golden
  grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden
  grype/presenter/table/__snapshots__/presenter_test.snap
  grype/presenter/table/presenter.go
  grype/presenter/table/presenter_test.go
  grype/version/version.go
  grype/version/version_test.go
Labels: enhancement

#2529 Improve DB metadata regarding data provenance
  cmd/grype/cli/commands/db_import.go
  cmd/grype/cli/commands/db_status.go
  cmd/grype/cli/commands/db_status_test.go
  cmd/grype/cli/commands/root.go
  grype/db/v6/db.go
  grype/db/v6/distribution/client.go
  grype/db/v6/distribution/client_test.go
  grype/db/v6/import_metadata.go
  grype/db/v6/import_metadata_test.go
  grype/db/v6/installation/curator.go
  grype/db/v6/installation/curator_test.go
  grype/db/v6/status.go
  grype/db/v6/vulnerability_provider.go
  grype/load_vulnerability_db.go
  grype/presenter/json/presenter.go
  grype/presenter/models/descriptor.go
  grype/presenter/models/document.go
  grype/presenter/models/presenter_bundle.go
  grype/vulnerability/provider.go
Labels: enhancement

#2550 Remove mitchellh dependencies
  go.mod
  go.sum
  grype/db/v5/pkg/qualifier/from_json.go
  grype/match/details.go
  grype/match/fingerprint.go
  grype/pkg/package.go
  grype/pkg/package_test.go
  grype/pkg/purl_provider.go
  grype/pkg/syft_sbom_provider.go
  grype/presenter/template/presenter.go
  internal/format/writer.go
Labels: changelog-ignore

#2553 `db list` should render out full URLs for text format
  cmd/grype/cli/commands/db_list.go
  cmd/grype/cli/commands/db_list_test.go
Labels: bug

#2556 Use data driven approach when detecting Alpine:edge and Debian:sid
  grype/db/v5/namespace/index.go
  grype/db/v5/namespace/index_test.go
  grype/db/v6/affected_package_store.go
  grype/db/v6/affected_package_store_test.go
  grype/db/v6/data.go
  grype/db/v6/vulnerability_provider.go
  grype/distro/distro.go
  grype/distro/distro_test.go
  grype/distro/test-fixtures/os/alpine-edge/etc/os-release
  grype/distro/test-fixtures/os/debian-sid/usr/lib/os-release
  grype/matcher/apk/matcher_test.go
  grype/matcher/internal/distro.go
  grype/matcher/msrc/matcher_test.go
  grype/pkg/qualifier/rpmmodularity/qualifier_test.go
  grype/presenter/models/distribution.go
  grype/search/distro.go
Labels: bug

#2568 Add CVSS metrics in search JSON output
  cmd/grype/cli/commands/internal/dbsearch/vulnerabilities.go
  cmd/grype/cli/commands/internal/dbsearch/vulnerabilities_test.go
  grype/db/v6/severity.go
  grype/db/v6/severity_test.go
  internal/cvss/metrics.go
  internal/cvss/metrics_test.go
Labels: enhancement
