Repository anchore/grype, pull requests merged in 2025-05, with the labels that each got.

#2587 Add risk score to results and sort by risk by default
  README.md
  cmd/grype/cli/cli.go
  cmd/grype/cli/commands/root.go
  cmd/grype/cli/options/grype.go
  cmd/grype/cli/options/sort_by.go
  go.mod
  go.sum
  grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterDir.golden
  grype/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxPresenterImage.golden
  grype/presenter/internal/test_helpers.go
  grype/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
  grype/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
  grype/presenter/models/sort.go
  grype/presenter/models/sort_test.go
  grype/presenter/models/vulnerability.go
  grype/presenter/models/vulnerability_metadata.go
  grype/presenter/sarif/presenter_test.go
  grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_directory.golden
  grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden
  grype/presenter/table/__snapshots__/presenter_test.snap
  grype/presenter/table/presenter.go
  grype/presenter/table/presenter_test.go
  grype/vulnerability/metadata.go
  grype/vulnerability/metadata_test.go
Labels: enhancement

#2660 minor: add CPE source to the help text
  cmd/grype/cli/commands/root.go
Labels: documentation

#2675 Parse java group ID and artifact ID from PURL when missing
  go.mod
  go.sum
  grype/pkg/package.go
  grype/pkg/package_test.go
  grype/pkg/purl_provider_test.go
Labels: bug

#2684 Updated Readme (CBL-Mariner is now Azure Linux)
  README.md
Labels: changelog-ignore

#2692 Always show results with json output for `db search` commands
  cmd/grype/cli/commands/db_search.go
  cmd/grype/cli/commands/db_search_vuln.go
Labels: bug
