Repository anchore/grype, pull requests merged in 2025-04, with the labels that each got.

#2572 Unpin go version in CI
  .github/actions/bootstrap/action.yaml
Labels: changelog-ignore

#2590 Recover from panic within a matcher
  grype/vulnerability_matcher.go
  grype/vulnerability_matcher_test.go
Labels: bug

#2571 feat: add sarif result level
  grype/presenter/sarif/presenter.go
  grype/presenter/sarif/presenter_test.go
  grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_directory.golden
  grype/presenter/sarif/test-fixtures/snapshot/TestSarifPresenter_image.golden
Labels: enhancement

#2589 Fix severity field in `db search vuln`
  cmd/grype/cli/commands/db_search_vuln.go
  cmd/grype/cli/commands/db_search_vuln_test.go
  internal/cvss/metrics.go
  internal/cvss/metrics_test.go
Labels: bug

#2591 Assume that empty versions should match on all possible versions
  grype/match/matches.go
  grype/matcher/internal/cpe.go
  grype/matcher/internal/cpe_test.go
  grype/matcher/internal/distro.go
  grype/matcher/internal/only_vulnerable_versions.go
Labels: bug

#2617 Add test for use statement
  go.mod
  go.sum
  grype/pkg/package_test.go
Labels: changelog-ignore

#2625 chore: improve release quality gate
  .github/workflows/release.yaml
Labels: changelog-ignore
