Repository anchore/grype, pull requests merged in 2025-07, with the labels that each got.

#2786 Remove pill pattern from table output
  grype/presenter/table/__snapshots__/presenter_test.snap
  grype/presenter/table/presenter.go
Labels: bug

#2789 chore: fix some minor issues in comments
  grype/db/v5/distribution/curator_test.go
  grype/db/v6/installation/curator_test.go
  grype/matcher/internal/only_vulnerable_targets.go
  grype/matcher/internal/only_vulnerable_versions.go
  grype/pkg/syft_sbom_provider_test.go
  grype/vex/openvex/implementation.go
Labels: documentation

#2800 chore: remove disallowed characters from hostname before test fixture cert generation
  grype/db/v5/distribution/test-fixtures/tls/generate-x509-cert-pair.sh
Labels: changelog-ignore

#2816 chore: revert credentials persistence for release
  .github/workflows/release.yaml
Labels: changelog-ignore

#2822 chore: add source completion testing
  go.mod
  go.sum
  grype/presenter/models/source_test.go
Labels: changelog-ignore

#2833 Add post-release workflow for install script
  .github/scripts/goreleaser-install.sh
  .github/scripts/update-version-file.sh
  .github/workflows/release-version-file.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  Taskfile.yaml
  install.sh
Labels: release
