Repository anchore/grype, pull requests merged in 2025-08, with the labels that each got.

#1826 feat(vex): CSAF support
  .bouncer.yaml
  cmd/grype/cli/commands/root.go
  cmd/grype/cli/commands/root_test.go
  go.mod
  go.sum
  grype/match/matcher_type.go
  grype/presenter/internal/test_helpers.go
  grype/vex/csaf/csaf.go
  grype/vex/csaf/csaf_test.go
  grype/vex/csaf/implementation.go
  grype/vex/csaf/implementation_test.go
  grype/vex/csaf/status.go
  grype/vex/openvex/implementation.go
  grype/vex/processor.go
  grype/vex/processor_test.go
  grype/vex/status/status.go
  grype/vex/testdata/vex-docs/csaf-demo1.json
  grype/vex/testdata/vex-docs/csaf-demo2.json
  grype/vulnerability_matcher_test.go
  test/integration/db_mock_test.go
  test/integration/match_by_image_test.go
  test/integration/test-fixtures/vex/csaf/affected.csaf.json
  test/integration/test-fixtures/vex/csaf/under_investigation.csaf.json
  test/integration/test-fixtures/vex/openvex/affected.openvex.json
  test/integration/test-fixtures/vex/openvex/under_investigation.openvex.json
Labels: enhancement, breaking-change

#2893 feat[raspbian]: support vulnerability matching for raspbian
  grype/db/v6/data.go
  grype/distro/distro_test.go
  grype/distro/test-fixtures/os/raspbian/etc/os-release
  grype/distro/type.go
Labels: enhancement, database

#2844 feat: detect patch numbers in fuzzy version comparison
  grype/version/fuzzy_constraint.go
  grype/version/fuzzy_constraint_test.go
Labels: bug

#2905 Present fix available version in grype JSON output
  grype/db/v6/vulnerability.go
  grype/db/v6/vulnerability_test.go
  grype/presenter/models/vulnerability.go
  grype/presenter/models/vulnerability_test.go
  grype/vulnerability/fix.go
Labels: bug
